### ISSUE TITLE
List items relating to the Customer Concerns at top

### ISSUE THREAD

**Issue by scaspers** [scaspers/CA-Portal#7]
We would like a way of noting if a checklist item is addressing a concern that the customer noted when dropping off vehicle.  Related issue on DigitalInspection [#114](https://github.com/DanielCaspers/DigitalInspection/issues/114)

We should have a separate section just above the full inspection list that shows the inspection items that were marked as such by the tech.

Title the new section something like:
"Issues you wanted looked at"
"What you were concerned about"
"Your vehicle concerns"

and then the full report below:
"Full inspection report"
"Other items inspected"

**Comment by DanielCaspers** [comment]
Option 3, we could make a 3rd tab (the default) which would be "Your concerns". @scaspers, @YoMurphy, thoughts?

**Comment by DanielCaspers** [comment]
@scaspers , please install on the server and demo. 

I've found a good representative order against the DI2 server
https://ca2.murphyauto.net/#/inspections/8a366d80-7c31-4ae9-aa15-daa66c9e7e23/priority


- [CA-Portal_Customer_CustomerConcerns01_DI2.zip](https://github.com/scaspers/CA-Portal/files/2153665/CA-Portal_Customer_CustomerConcerns01_DI2.zip)

- [CA-Portal_Customer_CustomerConcerns01_DI.zip](https://github.com/scaspers/CA-Portal/files/2153666/CA-Portal_Customer_CustomerConcerns01_DI.zip)

**Comment by DanielCaspers** [comment]
@scaspers , assigned to you for acceptance testing. Please refine any further criteria and report back, or unassign and close.

**Comment by DanielCaspers** [comment]
@scaspers @YoMurphy so I went back to the drawing board on the look and feel of this. After you mentioned the prominence of it, I realized I hadn't thought carefully enough about quite a few details and had bigger issues underlying things. 

Here were my overall goals for making tweaks in many places 
1) Adjust colors to make the background of the page stand out against the "material effect", which should make the important content "pop out" to the user.
2) Always make sure the customer concerns are open, accessible, and "in their face". No good reason to collapse it. 
3) Get rid of "grey on grey" readability issues

Thoughts?

![image](https://user-images.githubusercontent.com/6056563/42197839-63a54270-7e4a-11e8-92f1-c0f19761fe9d.png)

![image](https://user-images.githubusercontent.com/6056563/42197907-cd1c483e-7e4a-11e8-9aae-dccbf2883209.png)

![image](https://user-images.githubusercontent.com/6056563/42197929-d5d59bd8-7e4a-11e8-8525-8256b13efb32.png)

**Comment by DanielCaspers** [comment]
@scaspers @YoMurphy, I also suggest that we will get a much better result if we stop using the flat style of the accordion, and instead let it do it's "material magic". We've been circumventing style guidelines this whole time by getting the colors wrong and darkening the foreground instead of the background...

I think with these tweaks we just went from mostly good to A+. Looking forward to your thoughts.

![jul 2 2018 11_03 pm](https://user-images.githubusercontent.com/6056563/42198236-5e6c53aa-7e4c-11e8-926a-e790e6d7c362.gif)

**Comment by DanielCaspers** [comment]
[CA-Portal_Customer_CustomerConcerns02_DI.zip](https://github.com/scaspers/CA-Portal/files/2159909/CA-Portal_Customer_CustomerConcerns02_DI.zip)
[CA-Portal_Customer_CustomerConcerns02_DI2.zip](https://github.com/scaspers/CA-Portal/files/2159910/CA-Portal_Customer_CustomerConcerns02_DI2.zip)

**Comment by YoMurphy** [comment]
"material magic" ... more like "Danny Magic"!!!

**Comment by DanielCaspers** [comment]
[CA-Portal_Customer_CustomerConcerns03_DI2.zip](https://github.com/scaspers/CA-Portal/files/2196148/CA-Portal_Customer_CustomerConcerns03_DI2.zip)
[Ca-Portal_Customer_CustomerConcerns03_DI.zip](https://github.com/scaspers/CA-Portal/files/2196149/Ca-Portal_Customer_CustomerConcerns03_DI.zip)

**Comment by DanielCaspers** [comment]
[CA-Portal_ServiceWriter_CustomerConcerns01_DI2.zip](https://github.com/scaspers/CA-Portal/files/2196230/CA-Portal_ServiceWriter_CustomerConcerns01_DI2.zip)
[CA-Portal_ServiceWriter_CustomerConcerns01_DI.zip](https://github.com/scaspers/CA-Portal/files/2196236/CA-Portal_ServiceWriter_CustomerConcerns01_DI.zip)

**Comment by DanielCaspers** [comment]
@scaspers awaiting your acceptance to close. I was struggling to browser-compat test this prior to it being uploaded, so if you want me to vet this on multi OS / browser for SA, LMK.

**Comment by scaspers** [comment]
Look great in chrome.  
Looks like a major layout problem on firefox and win7/IE11. 

Did we ever talk about moving the unknown\no response items to the bottom?  I thought we had but I cannot find an issue on it.

**Comment by DanielCaspers** [comment]
I thought you said you wanted it on top in SA so Service Writers would be aware of anything unknown or missing as a top priority item to be aware of until they get further adjusted to the software?


[CA-Portal_ServiceWriter_CustomerConcerns02_DI2.zip](https://github.com/scaspers/CA-Portal/files/2196373/CA-Portal_ServiceWriter_CustomerConcerns02_DI2.zip)
[CA-Portal_ServiceWriter_CustomerConcerns02_DI.zip](https://github.com/scaspers/CA-Portal/files/2196378/CA-Portal_ServiceWriter_CustomerConcerns02_DI.zip)
